# Generated by Django 4.2.2 on 2023-07-02 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0002_userrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_record', to='nirab.record'),
        ),
    ]
