# Generated by Django 4.2.2 on 2023-07-02 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0005_recordimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recordimage',
            name='image_count',
        ),
        migrations.RemoveField(
            model_name='recordimage',
            name='record',
        ),
    ]
