# Generated by Django 4.2.2 on 2023-07-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0002_event_eventvenue_eventattendee_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mannager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventvenue',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
