# Generated by Django 4.2.2 on 2023-07-02 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nirab', '0003_event_mannager_alter_eventvenue_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='mannager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
