# Generated by Django 4.2.2 on 2023-07-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0008_record_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='photo_cout',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
