# Generated by Django 4.2.2 on 2023-07-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0009_record_photo_cout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='photo_cout',
        ),
        migrations.AddField(
            model_name='record',
            name='photo_count',
            field=models.IntegerField(default=0),
        ),
    ]
