# Generated by Django 4.2.2 on 2023-07-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0010_remove_record_photo_cout_record_photo_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='photo_count',
        ),
    ]
