# Generated by Django 4.2.2 on 2023-07-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0011_remove_record_photo_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordimage',
            name='image_count',
            field=models.IntegerField(default=0),
        ),
    ]
