# Generated by Django 4.2.2 on 2023-07-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0012_recordimage_image_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordimage',
            name='allowed_image_count',
            field=models.IntegerField(default=5),
        ),
    ]
