# Generated by Django 4.2.2 on 2023-07-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0014_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='record_mail_me',
            name='topic',
            field=models.CharField(choices=[('option1', 'HIRE ME'), ('option2', 'CONTACT ME'), ('option3', 'COLLABORATION REQUEST')], default='CONTACT ME', max_length=100),
        ),
    ]
