# Generated by Django 4.2.2 on 2023-07-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0015_record_mail_me_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record_mail_me',
            name='topic',
            field=models.CharField(choices=[('HIRE_ME', 'HIRE ME'), ('CONTACT_ME', 'CONTACT ME'), ('COLLABORATION', 'COLLABORATION REQUEST')], default='CONTACT_ME', max_length=100),
        ),
    ]
