# Generated by Django 4.2.2 on 2023-07-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0019_medication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medication',
        ),
    ]
