# Generated by Django 4.2.2 on 2023-07-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0021_medication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='generic_name',
            field=models.CharField(max_length=200),
        ),
    ]
