# Generated by Django 4.2.2 on 2023-07-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0022_alter_medication_generic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='price_analysis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medication',
            name='price',
            field=models.CharField(max_length=200),
        ),
    ]
