# Generated by Django 4.2.2 on 2023-07-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0024_medicationdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationdetails',
            name='contraindications_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='medicationdetails',
            name='dosage_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='medicationdetails',
            name='drug_class',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='medicationdetails',
            name='generic_name',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='medicationdetails',
            name='indication',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='medicationdetails',
            name='indication_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='medicationdetails',
            name='interaction_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='medicationdetails',
            name='pharmacology_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='medicationdetails',
            name='side_effects_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='medicationdetails',
            name='therapeutic_class_description',
            field=models.TextField(max_length=500),
        ),
    ]
