# Generated by Django 4.2.2 on 2023-07-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0025_alter_medicationdetails_contraindications_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='USP_prescription_classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usp_category', models.CharField(max_length=200)),
                ('usp_class', models.CharField(max_length=200)),
                ('usp_drug', models.CharField(max_length=200)),
                ('generic_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
