# Generated by Django 4.2.2 on 2023-07-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0026_usp_prescription_classification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='USP_prescription_classification',
        ),
    ]
