# Generated by Django 4.2.2 on 2023-07-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0028_classify_drug_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classify_Side_Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('indication', models.CharField(max_length=100)),
                ('side_effect', models.CharField(max_length=200)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
