# Generated by Django 4.2.2 on 2023-07-23 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0030_alter_classify_side_effect_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classify_side_effect',
            name='generic_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='nirab.medication'),
            preserve_default=False,
        ),
    ]
