# Generated by Django 4.2.2 on 2023-07-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0031_classify_side_effect_generic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classify_side_effect',
            name='generic_name',
            field=models.CharField(max_length=100),
        ),
    ]
