# Generated by Django 4.2.2 on 2023-07-24 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0033_alter_classify_side_effect_generic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classify_side_effect',
            name='generic_name',
        ),
        migrations.RemoveField(
            model_name='classify_side_effect',
            name='group',
        ),
        migrations.RemoveField(
            model_name='classify_side_effect',
            name='indication',
        ),
        migrations.RemoveField(
            model_name='classify_side_effect',
            name='score',
        ),
        migrations.RemoveField(
            model_name='classify_side_effect',
            name='side_effect',
        ),
    ]
