# Generated by Django 4.2.2 on 2023-07-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0034_remove_classify_side_effect_generic_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classify_side_effect',
            name='generic_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classify_side_effect',
            name='group',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classify_side_effect',
            name='indication',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classify_side_effect',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classify_side_effect',
            name='side_effect',
            field=models.TextField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
