# Generated by Django 4.2.2 on 2023-07-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0035_classify_side_effect_generic_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classify_CONTRADICTIONS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=200)),
                ('group', models.CharField(max_length=200)),
                ('indication', models.CharField(max_length=200)),
                ('contraindications_description', models.TextField(max_length=2000)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
