# Generated by Django 4.2.2 on 2023-07-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0036_classify_contradictions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classify_contradictions',
            old_name='contraindications_description',
            new_name='contraindication',
        ),
        migrations.AddField(
            model_name='classify_contradictions',
            name='contraindication_result',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
