# Generated by Django 4.2.2 on 2023-07-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0037_rename_contraindications_description_classify_contradictions_contraindication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classify_drug_class',
            name='generic_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
