# Generated by Django 4.2.2 on 2023-07-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0038_classify_drug_class_generic_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ques_Ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=1000)),
                ('answer', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
