# Generated by Django 4.2.2 on 2023-07-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0039_ques_ans'),
    ]

    operations = [
        migrations.CreateModel(
            name='med_Ques_Ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('generic_name', models.CharField(blank=True, max_length=200, null=True)),
                ('question', models.TextField(blank=True, max_length=1000, null=True)),
                ('answer', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Ques_Ans',
        ),
    ]
