# Generated by Django 4.2.2 on 2023-07-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0040_med_ques_ans_delete_ques_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='med_ques_ans',
            name='corrected_answer',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
