# Generated by Django 4.2.2 on 2023-07-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0041_med_ques_ans_corrected_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SELECTED_QUESTION_ANSWER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=200)),
                ('A_T_U_C', models.CharField(max_length=200)),
                ('A_S_E_C', models.CharField(max_length=200)),
                ('A_M_O_C', models.CharField(max_length=200)),
                ('W_T_A_D_C', models.CharField(max_length=200)),
                ('W_T_A_F_C', models.CharField(max_length=200)),
                ('I_W_C_N_T_T_C', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
