# Generated by Django 4.2.2 on 2023-07-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0042_selected_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presciption_drug_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=200)),
                ('drug_class', models.CharField(max_length=200)),
                ('heading', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
