# Generated by Django 4.2.2 on 2023-08-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0044_delete_classify_contradictions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='handwritten_text_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_handwritten', models.TextField(max_length=1000)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
