# Generated by Django 4.2.2 on 2023-08-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirab', '0045_handwritten_text_model_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handwritten_text_model',
            name='text_handwritten',
            field=models.TextField(max_length=5000),
        ),
    ]
